Repository ow2-proactive/proactive-examples, pull requests merged in 2018-05, with the labels that each got.

#137 added image segmentation tasks and workflows
  DeepLearning/METADATA.json
  DeepLearning/resources/catalog/AlexNet.xml
  DeepLearning/resources/catalog/DenseNet-161.xml
  DeepLearning/resources/catalog/Export_Model.xml
  DeepLearning/resources/catalog/Export_Results.xml
  DeepLearning/resources/catalog/FCN.xml
  DeepLearning/resources/catalog/Import_Image_Dataset.xml
  DeepLearning/resources/catalog/Import_Model.xml
  DeepLearning/resources/catalog/Predict_Image_Classification_Model.xml
  DeepLearning/resources/catalog/Predict_Segmentation.xml
  DeepLearning/resources/catalog/Predict_Text_Classification_Model.xml
  DeepLearning/resources/catalog/ResNet-18.xml
  DeepLearning/resources/catalog/SegNet.xml
  DeepLearning/resources/catalog/Train_Image_Classification_Model.xml
  DeepLearning/resources/catalog/Train_Segmentation.xml
  DeepLearning/resources/catalog/Train_Text_Classification_Model.xml
  DeepLearning/resources/catalog/UNet.xml
  DeepLearning/resources/catalog/VGG-16.xml
  DeepLearningWorkflows/METADATA.json
  DeepLearningWorkflows/resources/catalog/Image_Segmentation.xml
Labels: enhancement

#138 Changed FCN16 to SegNet in the Image Segmentation workflow
  DeepLearningWorkflows/resources/catalog/Image_Segmentation.xml
Labels: enhancement

#140 fix train/predict image segmentation file name and task name
  DeepLearning/resources/catalog/Predict_Image_Segmentation_Model.xml
  DeepLearning/resources/catalog/Train_Image_Segmentation_Model.xml
Labels: bug

#145 fixed export_results for any type image
  DeepLearning/resources/catalog/Export_Images.xml
  DeepLearning/resources/catalog/Export_Results.xml
  DeepLearning/resources/catalog/GRU.xml
  DeepLearning/resources/catalog/Import_Text_Dataset.xml
  DeepLearning/resources/catalog/LSTM.xml
  DeepLearning/resources/catalog/Predict_Image_Classification_Model.xml
  DeepLearning/resources/catalog/Predict_Image_Segmentation_Model.xml
  DeepLearning/resources/catalog/Predict_Text_Classification_Model.xml
  DeepLearning/resources/catalog/RNN.xml
  DeepLearning/resources/catalog/Train_Image_Classification_Model.xml
  DeepLearning/resources/catalog/Train_Image_Segmentation_Model.xml
  DeepLearning/resources/catalog/Train_Text_Classification_Model.xml
Labels: bug, enhancement

#153 data-visualization bucket updated
  DataVisualization/resources/catalog/Visdom_Bind_or_Start_Service.xml
  DataVisualization/resources/catalog/Visdom_Client_Example.xml
  DataVisualization/resources/catalog/Visdom_Plot_Example.xml
  DataVisualization/resources/catalog/Visdom_Realtime_Digit_Classification.xml
  DataVisualization/resources/catalog/Visdom_Service_Example.xml
  DataVisualization/resources/catalog/Visdom_Terminate_Service.xml
  DataVisualization/resources/catalog/Visdom_Terminate_Service_Until_Validation.xml
  DataVisualization/resources/catalog/Visdom_Visualize_Results.xml
Labels: enhancement

#157 deep-learning-bucket and image-segmentation workflow updated
  DeepLearning/resources/catalog/Export_Images.xml
  DeepLearning/resources/catalog/FCN.xml
  DeepLearning/resources/catalog/Import_Image_Dataset.xml
  DeepLearning/resources/catalog/Predict_Image_Segmentation_Model.xml
  DeepLearning/resources/catalog/SegNet.xml
  DeepLearning/resources/catalog/Train_Image_Segmentation_Model.xml
  DeepLearning/resources/catalog/UNet.xml
  DeepLearningWorkflows/resources/catalog/Image_Segmentation.xml
Labels: enhancement

#158 Visdom fixes
  DataVisualization/resources/catalog/Start_Visdom_Service.xml
  DataVisualization/resources/catalog/Stop_Visdom_Service.xml
  DataVisualization/resources/catalog/Stop_Visdom_Service_After_Validation.xml
  DataVisualization/resources/catalog/Visdom_Plot_Example.xml
  DataVisualization/resources/catalog/Visdom_Realtime_Digit_Classification.xml
  DataVisualization/resources/catalog/Visdom_Service_Example.xml
  LogAnalysis/resources/catalog/Anomaly_Detection_in_Apache_Logs.xml
  LogAnalysis/resources/catalog/Anomaly_Detection_in_HDFS_Blocks.xml
  LogAnalysis/resources/catalog/Anomaly_Detection_in_HDFS_Nodes.xml
  MLBasics/resources/catalog/Diabetics_Detection_using_K_Means.xml
  MLBasics/resources/catalog/House_Price_Prediction_using_Linear_Regression.xml
  MLBasics/resources/catalog/Iris_Flowers_Classification_using_Logistic_Regression.xml
Labels: enhancement

#160 fixed tasks name in the metadata.json
  DataVisualization/METADATA.json
Labels: enhancement

#161 fixed url doc for the new deep-learning tasks
  DeepLearning/resources/catalog/FCN.xml
  DeepLearning/resources/catalog/Predict_Image_Classification_Model.xml
  DeepLearning/resources/catalog/Predict_Image_Segmentation_Model.xml
  DeepLearning/resources/catalog/Predict_Text_Classification_Model.xml
  DeepLearning/resources/catalog/SegNet.xml
  DeepLearning/resources/catalog/Train_Image_Classification_Model.xml
  DeepLearning/resources/catalog/Train_Image_Segmentation_Model.xml
  DeepLearning/resources/catalog/Train_Text_Classification_Model.xml
  DeepLearning/resources/catalog/UNet.xml
Labels: enhancement

#168 organize deep learning and machine learning workflows bucket
  ImageAnalysis/METADATA.json
  ImageAnalysis/resources/catalog/Keras_Image_Classification.xml
  ImageAnalysis/resources/catalog/PyTorch_Image_Object_Segmentation.xml
  ImageAnalysis/resources/catalog/PyTorch_Train_Image_Object_Segmentation.xml
  ImageAnalysis/resources/catalog/TensorFlow_Image_Prediction.xml
  ImageAnalysis/resources/catalog/TensorFlow_Parallel_Image_Prediction.xml
  ImageAnalysis/resources/catalog/TensorFlow_Train_Image_Classifier.xml
  ImageAnalysis/resources/catalog/YOLO_Image_Anomaly_Detection.xml
  ImageAnalysis/resources/catalog/YOLO_Image_Object_Detection.xml
  LogAnalysis/resources/catalog/Anomaly_Detection_in_Apache_Logs.xml
  LogAnalysis/resources/catalog/Anomaly_Detection_in_HDFS_Blocks.xml
  LogAnalysis/resources/catalog/Anomaly_Detection_in_HDFS_Nodes.xml
  LogAnalysis/resources/catalog/Unsupervised_Anomaly_Detection.xml
  MLBasics/resources/catalog/Diabetics_Detection_using_K_Means.xml
  MLBasics/resources/catalog/House_Price_Prediction_using_Linear_Regression.xml
  MLBasics/resources/catalog/Iris_Flowers_Classification_using_Logistic_Regression.xml
  MLBasics/resources/catalog/Movies_Recommendation.xml
  MLNodeSource/resources/catalog/MachineLearning_NodeSource_Delete.xml
  MLNodeSource/resources/catalog/MachineLearning_NodeSource_Deploy.xml
  TextAnalysis/resources/catalog/One_Hot_Encode_Sequence_Data.xml
Labels: enhancement

#171 fixed log_analysis workflows from machine-learning bucket
  DataVisualization/resources/catalog/Visdom_Visualize_Results.xml
  LogAnalysis/resources/catalog/Anomaly_Detection_in_Apache_Logs.xml
  LogAnalysis/resources/catalog/Anomaly_Detection_in_HDFS_Blocks.xml
  LogAnalysis/resources/catalog/Anomaly_Detection_in_HDFS_Nodes.xml
  LogAnalysis/resources/catalog/Unsupervised_Anomaly_Detection.xml
Labels: enhancement

#172 fixed basic ml workflows
  MLBasics/resources/catalog/Diabetics_Detection_using_K_Means.xml
  MLBasics/resources/catalog/House_Price_Prediction_using_Linear_Regression.xml
  MLBasics/resources/catalog/Iris_Flowers_Classification_using_Logistic_Regression.xml
Labels: enhancement

#174 fixed deep learning tasks and workflows for data-visualization with visdom
  DataVisualization/resources/catalog/Visdom_Visualize_Results.xml
  DeepLearning/resources/catalog/Predict_Image_Classification_Model.xml
  DeepLearning/resources/catalog/Predict_Image_Segmentation_Model.xml
  DeepLearning/resources/catalog/Predict_Text_Classification_Model.xml
  DeepLearning/resources/catalog/Train_Image_Classification_Model.xml
  DeepLearning/resources/catalog/Train_Image_Segmentation_Model.xml
  DeepLearning/resources/catalog/Train_Text_Classification_Model.xml
  DeepLearningWorkflows/resources/catalog/Image_Segmentation.xml
Labels: enhancement

#175 organized the machine-learning-workflows and data-visualization buckets, workflows ordered by project
  DataVisualization/resources/catalog/Finish_Visdom_Service.xml
  DataVisualization/resources/catalog/Start_Visdom_Service.xml
  DataVisualization/resources/catalog/Stop_Visdom_Service.xml
  DataVisualization/resources/catalog/Visdom_Client_Example.xml
  DataVisualization/resources/catalog/Visdom_Plot_Example.xml
  DataVisualization/resources/catalog/Visdom_Realtime_Digit_Classification.xml
  DataVisualization/resources/catalog/Visdom_Service_Example.xml
  DataVisualization/resources/catalog/Visdom_Visualize_Results.xml
  DeepLearning/resources/catalog/Predict_Image_Segmentation_Model.xml
  LogAnalysis/resources/catalog/Anomaly_Detection_in_Apache_Logs.xml
  LogAnalysis/resources/catalog/Anomaly_Detection_in_HDFS_Blocks.xml
  LogAnalysis/resources/catalog/Anomaly_Detection_in_HDFS_Nodes.xml
  LogAnalysis/resources/catalog/Unsupervised_Anomaly_Detection.xml
  MLBasics/resources/catalog/Diabetics_Detection_using_K_Means.xml
  MLBasics/resources/catalog/House_Price_Prediction_using_Linear_Regression.xml
  MLBasics/resources/catalog/Iris_Flowers_Classification_using_Logistic_Regression.xml
  MLBasics/resources/catalog/Movies_Recommendation.xml
  TextAnalysis/resources/catalog/One_Hot_Encode_Sequence_Data.xml
Labels: enhancement
