Repository ow2-proactive/proactive-examples, pull requests merged in 2021-02, with the labels that each got.

#798 Renaming Model-service and DLaaS service
  DLaaS/resources/catalog/DLaaS.xml
  DLaaS/resources/catalog/Finish_DLaaS.xml
  MaaSDLPCA/METADATA.json
  MaaSDLPCA/resources/catalog/Finish_MaaS_DL.xml
  MaaSDLPCA/resources/catalog/MaaS_DL.xml
  MaaSMLPCA/METADATA.json
  MaaSMLPCA/resources/catalog/Deploy_ML_Model.xml
  MaaSMLPCA/resources/catalog/Finish_MaaS_ML.xml
  MaaSMLPCA/resources/catalog/MaaS_ML.xml
  MaaSMLPCA/resources/catalog/Pause_MaaS_ML.xml
  MaaSMLPCA/resources/catalog/Resume_MaaS_ML.xml
  MaaSMLPCA/resources/catalog/Update_MaaS_ML.xml
  MaaSMLPCA/resources/dataspace/certificate_mas.pem
  MaaSMLPCA/resources/dataspace/key_mas.pem
  ModelAsService/METADATA.json
  ModelAsService/resources/catalog/IRIS_Deploy_Flower_Classifier_Model.xml
  ModelAsService/resources/catalog/IRIS_Deploy_Predict_Flower_Classifier_Model.xml
  ModelAsService/resources/catalog/IRIS_Predict_From_Deployed_Model.xml
  ModelAsService/resources/catalog/MaaS_ML_Actions.xml
  ModelAsService/resources/catalog/MaaS_ML_Call_Prediction.xml
  ModelAsService/resources/catalog/MaaS_ML_Deploy_Model.xml
  ModelAsService/resources/catalog/MaaS_ML_Service_Start.xml
  ModelAsService/resources/catalog/Proactive_Call_Prediction_Service.xml
  ModelAsService/resources/catalog/Proactive_Model_Service_Actions.xml
  ModelAsService/resources/catalog/Proactive_Model_Service_Start.xml
  ModelAsServicePCA/resources/catalog/Finish_Model_Service.xml
  ModelAsServicePCA/resources/catalog/Pause_Model_Service.xml
  ModelAsServicePCA/resources/catalog/Resume_Model_Service.xml
  build.gradle
Labels: enhancement

#802 Fix some bugs in MaaS_DL and MaaS_ML
  ModelAsService/resources/catalog/IRIS_Deploy_Flower_Classifier_Model.xml
  ModelAsService/resources/catalog/IRIS_Deploy_Predict_Flower_Classifier_Model.xml
  ModelAsServiceResources/resources/catalog/dl_service-api.yaml
Labels: bug

#804 Fix secured Tensorboard PSA in proxified mode
  Tensorboard/resources/catalog/Tensorboard.xml
Labels: bug, enhancement

#807 AutoML fix submitted variables
  AutoML/resources/catalog/Multi_Tuners_Auto_ML.xml
Labels: enhancement

#811 add MaaS_DL actions
  MaaSDLPCA/METADATA.json
  MaaSDLPCA/resources/catalog/Deploy_DL_Model.xml
  MaaSDLPCA/resources/catalog/Redeploy_DL_Model.xml
  MaaSDLPCA/resources/catalog/Undeploy_DL_Model.xml
Labels: enhancement
