Repository ow2-proactive/proactive-examples, pull requests merged in 2021-03, with the labels that each got.

#814 Adding some features to the DDD (update, notification, removing old DDD)
  MaaSMLPCA/resources/catalog/Deploy_ML_Model.xml
  MaaSMLPCA/resources/catalog/MaaS_ML.xml
  MaaSMLPCA/resources/catalog/Update_MaaS_ML.xml
  ModelAsServiceResources/resources/catalog/ml_service-api.yaml
  ModelAsServiceResources/resources/catalog/ml_service.py
  ModelAsServiceScripts/resources/catalog/Deploy_Model_Service.py
Labels: enhancement

#815 Fix download MNIST issue
  DataVisualizationScripts/resources/catalog/Visdom_Train_CNN.py
Labels: enhancement

#816 Fix NVIDIA RAPIDS support on AI workflows.
  MachineLearningScripts/resources/catalog/Predict_Model.py
  MachineLearningScripts/resources/catalog/Train_Model.py
Labels: enhancement

#817 ML improvements
  MachineLearning/resources/dataspace/boston-houses-prices.csv
  MachineLearning/resources/dataspace/pima-indians-diabetes.csv
  MachineLearningScripts/resources/catalog/Train_Model.py
  MachineLearningWorkflows/resources/catalog/Train_Classification_Model_on_GPU.xml
  MachineLearningWorkflows/resources/catalog/Train_Multiple_Classification_Models_on_GPU.xml
  MachineLearningWorkflows/resources/catalog/Train_Multiple_Regression_Models_on_GPU.xml
  MachineLearningWorkflows/resources/catalog/Train_Regression_Model_on_GPU.xml
Labels: enhancement

#820 Fix ml workflows metadata
  MachineLearningWorkflows/METADATA.json
Labels: enhancement

#824 Fix MaaS_ML service project name
  MaaSMLPCA/resources/catalog/MaaS_ML.xml
  MaaSMLPCA/resources/catalog/Update_MaaS_ML.xml
Labels: enhancement

#825 Updated project name of Azure workflows
  ModelAsService/resources/catalog/Azure_Call_Deployed_Service.xml
  ModelAsService/resources/catalog/Azure_Delete_Deployed_Service.xml
  ModelAsService/resources/catalog/Azure_Deploy_Model.xml
  ModelAsService/resources/catalog/Azure_Model_Deployment_Example.xml
  ModelAsService/resources/catalog/Azure_Train_Deploy_Call_Diabetics_Detection_Service.xml
  ModelAsService/resources/catalog/Azure_Update_Deployed_Service.xml
Labels: enhancement

#826 Removed text analysis, renamed project names
  InMemoryWorkflows/METADATA.json
  InMemoryWorkflows/resources/catalog/In_Memory_Iris_Flowers_Classification.xml
  InMemoryWorkflows/resources/catalog/Start_IPython_Cluster.xml
  MachineLearningWorkflows/resources/catalog/Data_Anomaly_Detection.xml
  MachineLearningWorkflows/resources/catalog/Data_Fusion_And_Encoding.xml
  MachineLearningWorkflows/resources/catalog/Diabetics_Results_Visualization_Using_Tableau.xml
  MachineLearningWorkflows/resources/catalog/Train_Classification_Model_On_GPU.xml
  MachineLearningWorkflows/resources/catalog/Train_Multiple_Classification_Models_On_GPU.xml
  MachineLearningWorkflows/resources/catalog/Train_Multiple_Regression_Models_On_GPU.xml
  MachineLearningWorkflows/resources/catalog/Train_Regression_Model_On_GPU.xml
  TextAnalysis/METADATA.json
  TextAnalysis/resources/catalog/One_Hot_Encode_Sequence_Data.xml
  TextAnalysis/resources/test/scenarios.json
  build.gradle
Labels: enhancement

#828 Add MaaS_DL Client tasks
  ModelAsService/METADATA.json
  ModelAsService/resources/catalog/Deploy_DL_Model.xml
  ModelAsService/resources/catalog/MNIST_Model_Training_And_Deployment.xml
  ModelAsService/resources/catalog/MaaS_DL_Actions.xml
  ModelAsService/resources/catalog/MaaS_DL_Service_Start.xml
  ModelAsService/resources/catalog/Undeploy_DL_Model.xml
  ModelAsServiceScripts/METADATA.json
  ModelAsServiceScripts/resources/catalog/MaaS_DL_Deploy_Model.py
  ModelAsServiceScripts/resources/catalog/MaaS_DL_Undeploy_Model.py
Labels: enhancement

#827 Added support for running AutoML services (mongodb,visdom,tensorboard) on nodes with specific token
  AutoML/resources/catalog/AutoML_Python_Task_Template.xml
  AutoML/resources/catalog/CIFAR_100_Image_Classification.xml
  AutoML/resources/catalog/CIFAR_10_Image_Classification.xml
  AutoML/resources/catalog/Handwritten_Digit_Classification.xml
  AutoML/resources/catalog/Himmelblau_Function.xml
  AutoML/resources/catalog/Image_Object_Detection.xml
  AutoML/resources/catalog/Iris_Classification.xml
  AutoML/resources/catalog/Multi_Tuners_Auto_ML.xml
  AutoML/resources/catalog/Text_Generation.xml
  MongoDB/resources/catalog/Finish_MongoDB.xml
  MongoDB/resources/catalog/MongoDB.xml
  Tensorboard/resources/catalog/Finish_Tensorboard.xml
  Tensorboard/resources/catalog/Tensorboard.xml
  Visdom/resources/catalog/Finish_Visdom.xml
  Visdom/resources/catalog/Visdom.xml
Labels: enhancement

#829 New fix for Visdom_Realtime_Digit_Classification
  DataVisualization/resources/catalog/Visdom_Realtime_Digit_Classification.xml
  DataVisualizationScripts/resources/catalog/Visdom_Train_CNN.py
Labels: enhancement

#830 Added TensorFlow_Keras_Multi_Node_Multi_GPU workflow template
  AutoML/METADATA.json
  AutoML/resources/catalog/Python_Task_Template_For_AutoML.xml
  AutoML/resources/catalog/TensorFlow_Keras_Multi_Node_Multi_GPU.xml
Labels: enhancement

#832 Fix reference script path and documentation links
  ModelAsService/resources/catalog/Deploy_DL_Model.xml
  ModelAsService/resources/catalog/MaaS_DL_Actions.xml
  ModelAsService/resources/catalog/MaaS_DL_Service_Start.xml
  ModelAsService/resources/catalog/Undeploy_DL_Model.xml
  ModelAsServiceScripts/METADATA.json
Labels: bug

#837 Fusion data-visualization-scripts and data-visualization buckets
  DataVisualization/METADATA.json
  DataVisualization/resources/catalog/Visdom_Plots.xml
  DataVisualization/resources/catalog/Visdom_Plots_Example.xml
  DataVisualization/resources/catalog/Visdom_Plots_Script.py
  DataVisualization/resources/catalog/Visdom_Realtime_Digit_Classification.xml
  DataVisualization/resources/catalog/Visdom_Train_CNN_Script.py
  DataVisualization/resources/catalog/Visdom_Visualize_Results.xml
  DataVisualization/resources/catalog/Visdom_Visualize_Results_Script.py
  DataVisualizationScripts/METADATA.json
  LogAnalysis/resources/catalog/Anomaly_Detection_In_Apache_Logs.xml
  LogAnalysis/resources/catalog/Anomaly_Detection_In_HDFS_Blocks.xml
  LogAnalysis/resources/catalog/Anomaly_Detection_In_HDFS_Nodes.xml
  MachineLearningWorkflows/resources/catalog/Diabetics_Detection_Using_K_Means.xml
  MachineLearningWorkflows/resources/catalog/House_Price_Prediction_Using_Linear_Regression.xml
  MachineLearningWorkflows/resources/catalog/Iris_Flowers_Classification_Using_Logistic_Regression.xml
  build.gradle
  ordered_bucket_list
Labels: enhancement

#839 Fusion of model-as-service-scripts and model-as-service-resources with model-as-service
  MaaSDLPCA/resources/catalog/MaaS_DL.xml
  MaaSMLPCA/resources/catalog/MaaS_ML.xml
  ModelAsService/METADATA.json
  ModelAsService/resources/catalog/Azure_Call_Deployed_Service.xml
  ModelAsService/resources/catalog/Azure_Call_Deployed_Service_Script.py
  ModelAsService/resources/catalog/Azure_Delete_Deployed_Service.xml
  ModelAsService/resources/catalog/Azure_Delete_Deployed_Service_Script.py
  ModelAsService/resources/catalog/Azure_Deploy_Model.xml
  ModelAsService/resources/catalog/Azure_Deploy_Model_Script.py
  ModelAsService/resources/catalog/Azure_Model_Deployment_Example.xml
  ModelAsService/resources/catalog/Azure_Train_Deploy_Call_Diabetics_Detection_Service.xml
  ModelAsService/resources/catalog/Azure_Update_Deployed_Service.xml
  ModelAsService/resources/catalog/Azure_Update_Deployed_Service_Script.py
  ModelAsService/resources/catalog/Deploy_DL_Model.xml
  ModelAsService/resources/catalog/IRIS_Deploy_Flower_Classifier_Model.xml
  ModelAsService/resources/catalog/IRIS_Deploy_Predict_Flower_Classifier_Model.xml
  ModelAsService/resources/catalog/MNIST_Model_Training_And_Deployment.xml
  ModelAsService/resources/catalog/MaaS_DL_Deploy_Model.xml
  ModelAsService/resources/catalog/MaaS_DL_Deploy_Model_Script.py
  ModelAsService/resources/catalog/MaaS_DL_Service_Start.xml
  ModelAsService/resources/catalog/MaaS_DL_Undeploy_Model.xml
  ModelAsService/resources/catalog/MaaS_DL_Undeploy_Model_Script.py
  ModelAsService/resources/catalog/MaaS_ML_Call_Prediction.xml
  ModelAsService/resources/catalog/MaaS_ML_Call_Prediction_Script.py
  ModelAsService/resources/catalog/MaaS_ML_Deploy_Model.xml
  ModelAsService/resources/catalog/MaaS_ML_Deploy_Model_Script.py
  ModelAsService/resources/catalog/MaaS_ML_Service_Start.xml
  ModelAsService/resources/catalog/MaaS_Post_Script.groovy
  ModelAsService/resources/catalog/MaaS_Pre_Script.py
  ModelAsService/resources/catalog/MaaS_Start_Post_Script.groovy
  ModelAsService/resources/catalog/Undeploy_DL_Model.xml
  ModelAsService/resources/catalog/dl_service-api.yaml
  ModelAsService/resources/catalog/dl_service.py
  ModelAsService/resources/catalog/ml_service-api.yaml
  ModelAsService/resources/catalog/ml_service.py
  ModelAsServiceResources/METADATA.json
  ModelAsServiceScripts/METADATA.json
  ModelAsServiceScripts/resources/catalog/Deploy_Model_Service.py
  build.gradle
  ordered_bucket_list
Labels: enhancement

#838 Create PSA services management workflows
  COCOAnnotator/METADATA.json
  COCOAnnotator/resources/catalog/COCO_Annotator_Service.xml
  JupyterLab/METADATA.json
  JupyterLab/resources/catalog/Jupyterlab_Service.xml
  MaaSDLPCA/METADATA.json
  MaaSDLPCA/resources/catalog/MaaS_DL_Service.xml
  MaaSMLPCA/METADATA.json
  MaaSMLPCA/resources/catalog/MaaS_ML_Service.xml
  MongoDB/METADATA.json
  MongoDB/resources/catalog/MongoDB_Service.xml
  MySQL/METADATA.json
  MySQL/resources/catalog/MySQL_Service.xml
  PostgreSQL/METADATA.json
  PostgreSQL/resources/catalog/PostgreSQL_Service.xml
  Tensorboard/METADATA.json
  Tensorboard/resources/catalog/Tensorboard_Service.xml
  Visdom/METADATA.json
  Visdom/resources/catalog/Visdom_Service.xml
Labels: enhancement

#844 update maas_dl PSA doc links
  MaaSDLPCA/resources/catalog/Deploy_DL_Model.xml
  MaaSDLPCA/resources/catalog/Finish_MaaS_DL.xml
  MaaSDLPCA/resources/catalog/MaaS_DL.xml
  MaaSDLPCA/resources/catalog/Redeploy_DL_Model.xml
  MaaSDLPCA/resources/catalog/Undeploy_DL_Model.xml
Labels: enhancement

#846 Fix MaaS_ML, AutoML and Tensorboard Plots Example
  AutoML/resources/catalog/Multi_Tuners_Auto_ML.xml
  DataVisualization/resources/catalog/Tensorboard_Plots_Example.xml
  ModelAsService/resources/catalog/IRIS_Deploy_Flower_Classifier_Model.xml
  ModelAsService/resources/catalog/IRIS_Deploy_Predict_Flower_Classifier_Model.xml
Labels: enhancement

#841 Update jre
  JobAnalysis/resources/catalog/Gantt_chart.xml
  NodeSources/resources/catalog/AwsEC2Cloud.json
  NodeSources/resources/catalog/AwsEC2CloudElastic.json
  NodeSources/resources/catalog/AzureCloud.json
  NodeSources/resources/catalog/GoogleComputeEngine.json
  NodeSources/resources/catalog/GoogleComputeEngineElastic.json
  NodeSources/resources/catalog/OVH.json
  NodeSources/resources/catalog/OVHElastic.json
  NodeSources/resources/catalog/Openstack_Liberty.json
  NodeSources/resources/catalog/Openstack_Rocky.json
Labels: enhancement

#845 Update post service start script with enableActions param
  COCOAnnotator/resources/catalog/COCO_Annotator_Service.xml
  JupyterLab/resources/catalog/Jupyterlab_Service.xml
  Knime/resources/catalog/Knime.xml
  MaaSDLPCA/resources/catalog/MaaS_DL_Service.xml
  MaaSMLPCA/resources/catalog/MaaS_ML_Service.xml
  ModelAsService/resources/catalog/MaaS_Post_Script.groovy
  MongoDB/resources/catalog/MongoDB_Service.xml
  MySQL/resources/catalog/MySQL_Service.xml
  PcaScripts/resources/catalog/Post_Service_Start.groovy
  PcaScripts/resources/catalog/Service_Start.groovy
  PostgreSQL/resources/catalog/PostgreSQL_Service.xml
  Tensorboard/resources/catalog/Tensorboard_Service.xml
  Visdom/resources/catalog/Visdom_Service.xml
Labels: enhancement

#849 Added Stop Signal to AutoML
  AutoML/resources/catalog/Multi_Tuners_Auto_ML.xml
Labels: enhancement

#850 Fixed registerService in Service_Start
  PcaScripts/resources/catalog/Service_Start.groovy
Labels: enhancement

#852 Improved Service_Start, Improved AutoML
  AutoML/resources/catalog/Multi_Tuners_Auto_ML.xml
  PcaScripts/resources/catalog/Service_Start.groovy
Labels: enhancement

#853 Improve regestering services in PSA management workflows
  COCOAnnotator/resources/catalog/COCO_Annotator_Service.xml
  DatabaseServices/resources/catalog/PostgreSQL_Database_Interaction.xml
  JupyterLab/resources/catalog/Jupyterlab_Service.xml
  MaaSDLPCA/resources/catalog/MaaS_DL_Service.xml
  MaaSMLPCA/resources/catalog/MaaS_ML_Service.xml
  MongoDB/resources/catalog/MongoDB_Service.xml
  MySQL/resources/catalog/MySQL_Service.xml
  PcaScripts/METADATA.json
  PcaScripts/resources/catalog/Post_Service_Start.groovy
  PostgreSQL/resources/catalog/PostgreSQL.xml
  PostgreSQL/resources/catalog/PostgreSQL_Service.xml
  Tensorboard/resources/catalog/Tensorboard_Service.xml
  Visdom/resources/catalog/Visdom_Service.xml
Labels: bug, enhancement

#854 Fix Service_Start enableActions arg bug
  PcaScripts/resources/catalog/Service_Start.groovy
Labels: bug

#856 Added R task template for AutoML
  AutoML/METADATA.json
  AutoML/resources/catalog/R_Task_Template_For_AutoML.xml
Labels: enhancement

#857 MaaS refactoring
  ModelAsService/resources/catalog/MaaS_DL_Deploy_Model_Script.py
  ModelAsService/resources/catalog/MaaS_DL_Undeploy_Model_Script.py
  ModelAsService/resources/catalog/MaaS_ML_Call_Prediction_Script.py
  ModelAsService/resources/catalog/MaaS_ML_Deploy_Model_Script.py
  ModelAsService/resources/catalog/MaaS_Pre_Script.py
  ModelAsService/resources/catalog/dl_service.py
  ModelAsService/resources/catalog/ml_service.py
Labels: enhancement

#858 Fix pip install packages on MaaS
  MaaSDLPCA/resources/catalog/Deploy_DL_Model.xml
  MaaSDLPCA/resources/catalog/Redeploy_DL_Model.xml
  MaaSDLPCA/resources/catalog/Undeploy_DL_Model.xml
  MaaSMLPCA/resources/catalog/Deploy_ML_Model.xml
  MaaSMLPCA/resources/catalog/Update_MaaS_ML.xml
Labels: enhancement

#859 Fixed some workflows in the auto-ml-optimization bucket
  AutoML/resources/catalog/Handwritten_Digit_Classification.xml
  AutoML/resources/catalog/Iris_Classification.xml
  AutoML/resources/catalog/Python_Task_Template_For_AutoML.xml
  AutoML/resources/catalog/R_Task_Template_For_AutoML.xml
Labels: enhancement
